/* Plugin Template generated by Pawn Studio */
#pragma newdecls required
#include <sourcemod>

int IMPULS_FLASHLIGHT = 100;
float PressTime[MAXPLAYERS+1];
 
int Mode; 
bool EnableSuvivor; 
bool EnableInfected; 
ConVar l4d_nt_team;
ConVar g_cvGameMode;

public Plugin myinfo = 
{
	name = "Night Vision",
	author = "Pan Xiaohai & Mr. Zero, HatsuneImagine",
	description = "<- Description ->",
	version = "1.1",
	url = "<- URL ->"
}

public void OnPluginStart()
{
	RegConsoleCmd("sm_nightvision", sm_nightvision);
	l4d_nt_team = CreateConVar("l4d_nt_team", "1", "0:关闭, 1:向生还者和感染者开放, 2:向生还者开放, 3:向感染者开放", FCVAR_NONE);	
	AutoExecConfig(true, "l4d_nightvision"); 
	HookConVarChange(l4d_nt_team, ConVarChange);
	GetConVar();
}

public void OnMapStart()
{
	g_cvGameMode = FindConVar("mp_gamemode");
}

public void ConVarChange(ConVar convar, const char[] oldValue, const char[] newValue)
{
	GetConVar(); 
}

void GetConVar()
{
	Mode = GetConVarInt(l4d_nt_team);
	EnableSuvivor = (Mode == 1 || Mode == 2);
	EnableInfected = (Mode == 1 || Mode == 3);
}

public Action sm_nightvision(int client, int args)
{
	if(IsClientInGame(client)) SwitchNightVision(client);
	return Plugin_Handled;
}

//code from "Block Flashlight",
public Action OnPlayerRunCmd(int client, int &buttons, int &impuls, float vel[3], float angles[3], int &weapon)
{
	if(Mode == 0) return Plugin_Continue;
	if(impuls == IMPULS_FLASHLIGHT)
	{
		int team = GetClientTeam(client);
		if(team == 2 && EnableSuvivor)
		{		 	
			float time = GetEngineTime();
			if(time - PressTime[client] < 0.3)
			{
				SwitchNightVision(client); 				 
			}
			PressTime[client] = time;
		}	 
		if(team == 3 && EnableInfected)
		{
			float time = GetEngineTime();
			if(time - PressTime[client] > 0.1)
			{
				SwitchNightVision(client); 
			}
			PressTime[client] = time;			 
		}
	}
	
	return Plugin_Handled;
}

void SwitchNightVision(int client)
{
	int team = GetClientTeam(client);
	char sGameMode[32];
	g_cvGameMode.GetString(sGameMode, sizeof sGameMode);
	if(team == 2 && (StrContains(sGameMode, "versus") > -1 || StrContains(sGameMode, "scavenge") > -1)) return;

	int d = GetEntProp(client, Prop_Send, "m_bNightVisionOn");
	if(d == 0)
	{
		SetEntProp(client, Prop_Send, "m_bNightVisionOn",1); 
		PrintHintText(client, "夜视仪已开启");
		
	}
	else
	{
		SetEntProp(client, Prop_Send, "m_bNightVisionOn",0);
		PrintHintText(client, "夜视仪已关闭");	
	}
}
